import { NextResponse } from "next/server";
import dbConnect from "@/app/lib/db";
import { sendEmail } from "@/app/lib/email";
import Task from "@/app/models/Task";

export async function GET(req: Request) {
  await dbConnect;

    const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const now = new Date();

  // Find tasks whose due date has passed and not notified
  const overdueTasks = await Task.find({
    dueDate: { $lte: now },
    completed: false,
  });
   const emailSubject="Password Reset Request from Healthrive"
          const emailtext=`The task  is past due.`
          const emailHTML=`<p>Dear DrChioma, There is a pending task which yet to be done, If you done this, Please make sure to mart this complete in your healthrive dashboard. <br> Note: This is autogenerated email, Please do not reply to this! 
      <br> Healthrive Dashboard</p>`
  for (const task of overdueTasks) {
   
              await sendEmail("abdurrehman1722@gmail.com",emailSubject,emailtext,emailHTML);


    // Optional: mark as notified to avoid repeated emails
    task.notified = true;
    await task.save();
  }

  return NextResponse.json({ success: true, sent: overdueTasks.length });
}
